# Generated by Django 4.2.21 on 2025-05-17 12:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=100, verbose_name='نام صفحه')),
                ('username', models.CharField(max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='نام کاربری')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='بیوگرافی')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instagram_pages/', verbose_name='تصویر پروفایل')),
                ('followers_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دنبال\u200cکنندگان')),
                ('following_count', models.PositiveIntegerField(default=0, verbose_name='تعداد دنبال\u200cشوندگان')),
                ('posts_count', models.PositiveIntegerField(default=0, verbose_name='تعداد پست\u200cها')),
                ('average_likes', models.PositiveIntegerField(default=0, verbose_name='میانگین لایک')),
                ('average_comments', models.PositiveIntegerField(default=0, verbose_name='میانگین کامنت')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'صفحه اینستاگرام',
                'verbose_name_plural': 'صفحات اینستاگرام',
                'ordering': ['-followers_count'],
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زیرموضوع')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام موضوع')),
                ('icon', models.ImageField(upload_to='topic/', verbose_name='آیکون')),
                ('sub_topics', models.ManyToManyField(blank=True, to='stories.subtopic', verbose_name='زیرموضوع\u200cها')),
            ],
        ),
        migrations.CreateModel(
            name='StoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('story', models.ImageField(upload_to='images/', verbose_name='استوری')),
                ('feeling', models.CharField(choices=[('happy', 'شاد'), ('sad', 'غمگین'), ('angry', 'عصبانی'), ('calm', 'آرام'), ('excited', 'هیجان\u200cزده')], max_length=20, verbose_name='احساس')),
                ('ironic', models.CharField(choices=[('yes', 'بله'), ('no', 'خیر'), ('somewhat', 'تا حدی')], max_length=10, verbose_name='رویکرد')),
                ('tone', models.CharField(choices=[('formal', 'رسمی'), ('informal', 'غیررسمی'), ('friendly', 'دوستانه'), ('authoritative', 'مقتدرانه')], max_length=20, verbose_name='لحن')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='توضیحات')),
                ('story_text', models.TextField(blank=True, max_length=250, null=True, verbose_name='متن استوری')),
                ('story_type', models.CharField(choices=[('image', 'عکس'), ('video', 'ویدئو'), ('text', 'متن')], max_length=20, verbose_name='جنس استوری')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.instagrampage', verbose_name='صفحه')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampage',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.subtopic', verbose_name='زیرموضوع'),
        ),
        migrations.AddField(
            model_name='instagrampage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagrampage', to='stories.topic', verbose_name='موضوع'),
        ),
    ]
