# Generated by Django 4.2.21 on 2025-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_alter_storymodel_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='story',
            field=models.FileField(upload_to='images/', verbose_name='استوری'),
        ),
    ]
