# Generated by Django 4.2.21 on 2025-05-25 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_alter_storymodel_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته',
                'verbose_name_plural': 'دسته ها',
            },
        ),
        migrations.AlterModelOptions(
            name='storymodel',
            options={'verbose_name': 'صفحه استوری', 'verbose_name_plural': 'صفحات استوری'},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'verbose_name': 'زیر موضوع', 'verbose_name_plural': 'زیر موضوع'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'موضوع', 'verbose_name_plural': 'موضوعات'},
        ),
        migrations.AddField(
            model_name='instagrampage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.category', verbose_name='دسته'),
        ),
    ]
