# Generated by Django 4.2.21 on 2025-05-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_category_alter_storymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymodel',
            name='feeling',
            field=models.CharField(choices=[('شاد', 'شاد'), ('غمگین', 'غمگین'), ('عصبانی', 'عصبانی'), ('آرام', 'آرام'), ('هیجان\u200cزده', 'هیجان\u200cزده')], max_length=20, verbose_name='احساس'),
        ),
        migrations.AlterField(
            model_name='storymodel',
            name='ironic',
            field=models.CharField(choices=[('بله', 'بله'), ('خیر', 'خیر'), ('تا حدی', 'تا حدی')], max_length=10, verbose_name='رویکرد'),
        ),
        migrations.AlterField(
            model_name='storymodel',
            name='story_type',
            field=models.CharField(choices=[('عکس', 'عکس'), ('ویدئو', 'ویدئو'), ('متن', 'متن')], max_length=20, verbose_name='جنس استوری'),
        ),
        migrations.AlterField(
            model_name='storymodel',
            name='tone',
            field=models.CharField(choices=[('رسمی', 'رسمی'), ('غیررسمی', 'غیررسمی'), ('دوستانه', 'دوستانه'), ('مقتدرانه', 'مقتدرانه')], max_length=20, verbose_name='لحن'),
        ),
    ]
