# Generated by Django 4.2.21 on 2025-05-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_storymodel_feeling_alter_storymodel_ironic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='تصویر دسته'),
        ),
    ]
