# Generated by Django 4.2.21 on 2025-05-31 05:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_category_category_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('jalali_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ جلالی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تحلیل',
                'verbose_name_plural': 'تحلیل',
            },
        ),
    ]
