# Generated by Django 4.2.21 on 2025-06-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_dayanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampage',
            name='gender',
            field=models.CharField(choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر / مشخص نشده')], default='unknown', max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AddField(
            model_name='instagrampage',
            name='political_orientation',
            field=models.CharField(choices=[('osolgara', 'اصولگرا'), ('eslahtalab', 'اصلاح طلب'), ('moanedam', 'معاند عام'), ('saltanattalab', 'سلطنت طلب'), ('monafegh', 'منافق'), ('taghribanhamso', 'تقریبا همسو'), ('taghribannahamso', 'تقریبا ناهمسو')], default='unknown', max_length=20, verbose_name='گرایش سیاسی'),
        ),
    ]
