# Generated by Django 4.2.21 on 2025-06-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_instagrampage_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampage',
            name='orientation',
            field=models.CharField(choices=[('ekhlalgar', 'اخلالگر'), ('khakestari', 'خاکستری'), ('hamso', 'همسو (ارزشی)')], default='unknown', max_length=20, verbose_name='گرایش'),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='gender',
            field=models.CharField(choices=[('male', 'آقا'), ('female', 'خانم'), ('other', 'نامشخص')], default='unknown', max_length=10, verbose_name='جنسیت'),
        ),
    ]
