# Generated by Django 4.2.21 on 2025-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_instagrampage_orientation_alter_instagrampage_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampage',
            name='location',
            field=models.CharField(choices=[('in', 'داخل'), ('out', 'خارج'), ('other', 'نامشخص')], default='unknown', max_length=20, verbose_name='موقعیت'),
        ),
    ]
