# Generated by Django 4.2.21 on 2025-06-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_instagrampage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampage',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'آقا'), ('female', 'خانم'), ('other', 'نامشخص')], default='unknown', max_length=10, null=True, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='location',
            field=models.CharField(blank=True, choices=[('in', 'داخل'), ('out', 'خارج'), ('other', 'نامشخص')], default='unknown', max_length=20, null=True, verbose_name='موقعیت'),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='orientation',
            field=models.CharField(blank=True, choices=[('ekhlalgar', 'اخلالگر'), ('khakestari', 'خاکستری'), ('hamso', 'همسو (ارزشی)')], default='unknown', max_length=20, null=True, verbose_name='گرایش'),
        ),
        migrations.AlterField(
            model_name='instagrampage',
            name='political_orientation',
            field=models.CharField(blank=True, choices=[('osolgara', 'اصولگرا'), ('eslahtalab', 'اصلاح طلب'), ('moanedam', 'معاند عام'), ('saltanattalab', 'سلطنت طلب'), ('monafegh', 'منافق'), ('taghribanhamso', 'تقریبا همسو'), ('taghribannahamso', 'تقریبا ناهمسو')], default='unknown', max_length=20, null=True, verbose_name='گرایش سیاسی'),
        ),
    ]
