# Generated by Django 4.2.21 on 2025-06-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_alter_instagrampage_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagrampage',
            name='category',
        ),
        migrations.AddField(
            model_name='storymodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.category', verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='storymodel',
            name='ironic',
            field=models.CharField(choices=[('همسو', 'همسو'), ('ناهمسو', 'ناهمسو'), ('نامشخص', 'نامشخص')], max_length=10, verbose_name='رویکرد'),
        ),
        migrations.AlterField(
            model_name='storymodel',
            name='tone',
            field=models.CharField(choices=[('رسمی', 'رسمی'), ('غیررسمی', 'غیررسمی'), ('دوستانه', 'دوستانه'), ('مقتدرانه', 'مقتدرانه'), ('کنایی', 'کنایی')], max_length=20, verbose_name='لحن'),
        ),
    ]
