# Generated by Django 4.2.21 on 2025-06-07 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_remove_instagrampage_category_storymodel_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stories.category', verbose_name='دسته'),
        ),
    ]
